export const SET_USER = "SET_USER";
export const LOADING_USER = "LOADING_USER";
export const USER_ERROR = "USER_ERROR";
export const GAMES_ERROR = "GAMES_ERROR";
export const SET_GAMES = "SET_GAMES";
export const SET_GAME_SETTINGS = "SET_GAME_SETTINGS";
export const SET_GAME_FIELD_SETTINGS = "SET_GAME_FIELD_SETTINGS";
export const SET_GAME_PLAYERS = "SET_GAME_PLAYERS";

export const actionTypes = {
  CHECK_USER: "CHECK_USER",
  LOGIN_USER: "LOGIN_USER",
  REGISTER_USER: "REGISTER_USER",
  LOGOUT_USER: "LOGOUT_USER",
  GET_GAMES: "GET_GAMES",
  SET_GAME_NAME: "SET_GAME_NAME",
  SET_GAME_FIELD_HEIGHT: "SET_GAME_FIELD_HEIGHT",
  SET_GAME_FIELD_WIDTH: "SET_GAME_FIELD_WIDTH",
  SET_GAME_NEUTRAL_PLANETS_COUNT: "SET_GAME_NEUTRAL_PLANETS_COUNT",
  ADD_PLAYER: "ADD_PLAYER",
  ADD_USER_AS_PLAYER: "ADD_USER_AS_PLAYER",
  REMOVE_PLAYER: "REMOVE_PLAYER",
};
